app1/urls.py
from app1.views import *
from django.urls import path

app_name="something"

urlpatterns=[
    path('response/',response,name='response'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('urlnavigation/',urlnavigation,name='urlnavigation')
]

project4/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def response(request):
    return render(request,'response.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def urlnavigation(request):
    return render(request,'urlnavigation.html')

templates/response.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <center>
        <h1>Hello</h1>
        <h2>How are you</h2>
        <a href="{% url 'nothing:urlnavigation' %}">
            <h1>Response of urlnavigation</h1>
        </a>
    </center>
</body>

</html>

templates/urlnavigation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <center>
        <h1>Hello</h1>
        <h1>Iam good and what about you</h1>
    </center>
    <a href="{% url'something:response' %}"></a>
    <h1>Response of html</h1>
</body>

</html>